import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'

import {
  api,
  ApiError,
  type RecommendItem,
} from '../api/client'
import { GradientChart } from '../components/GradientChart'
import { PlanRow } from '../components/PlanRow'
import { RiskPanel } from '../components/RiskPanel'
import { ErrorNote, SourceLink, WarningList } from '../components/StateBlocks'
import { formatNumber, formatRank, formatPlanCount, formatTuition } from '../lib/format'
import { scrollToElement, useAsync } from '../lib/hooks'
import { UNIT_TYPE_LABEL, provinceLabel } from '../lib/labels'
import { isProfileComplete, useProfileStore } from '../store/profile'
import { usePlanStore } from '../store/plan'

/**
 * 志愿表（AGENTS.md §8.2 `/plan`）：拖拽排序 · 分层配色 · 梯度分布图 · 缺额提示 ·
 * 风险面板（HIGH 级阻断式）· 导出。
 *
 * 状态纪律：界面上显示的志愿顺序**始终来自后端返回的 `plan.items`**
 * （拖拽时先用本地 `draftOrder` 乐观展示，提交后立刻用服务端结果覆盖），
 * 避免出现"界面看着改了、后端没改"这种在志愿填报里不可接受的错位。
 */
export function PlanBoardPage() {
  const [searchParams, setSearchParams] = useSearchParams()
  const profile = useProfileStore()
  const planStore = usePlanStore()
  const { planId, setPlanId, setBundle } = planStore
  const bundle = planStore.bundle
  const payload = bundle?.data ?? null

  const [busy, setBusy] = useState(false)
  const [error, setError] = useState<unknown>(null)
  const [order, setOrder] = useState<string[] | null>(null)
  const [dragIndex, setDragIndex] = useState<number | null>(null)
  const [dropIndex, setDropIndex] = useState<number | null>(null)
  const [acknowledged, setAcknowledged] = useState(false)
  const [showAdd, setShowAdd] = useState(false)
  const [autoGenerated, setAutoGenerated] = useState(false)

  const studentId = profile.studentId
  const complete = isProfileComplete(profile.student)

  // 载入已有志愿表
  const loaded = useAsync(async () => {
    if (!planId) return null
    return await api.plans.get(planId)
  }, [planId])

  useEffect(() => {
    if (loaded.data) setBundle(loaded.data)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [loaded.data])

  const generate = useCallback(async () => {
    if (!studentId) return
    setBusy(true)
    setError(null)
    try {
      // ★ ADR-022：**不传 filters** —— 后端直接按档案里的筛选与偏好生成，
      //   与推荐列表同一份口径（考生在建档向导第 4 步只填一次）。
      const response = await api.plans.generate({
        student_id: studentId,
        preference_order: planStore.preferenceOrder.length ? planStore.preferenceOrder : null,
        obey_adjustment: planStore.obeyAdjustment,
      })
      setPlanId(response.data.plan.id)
      setBundle(response)
      setOrder(null)
      setAcknowledged(false)
      setAutoGenerated(true)
    } catch (caught) {
      setError(caught)
    } finally {
      setBusy(false)
    }
  }, [studentId, planStore.preferenceOrder, planStore.obeyAdjustment, setPlanId, setBundle])

  // 从推荐页带 ?generate=1 过来时自动生成一次
  const shouldGenerate = searchParams.get('generate') === '1'
  const generateRef = useRef(false)
  useEffect(() => {
    if (!shouldGenerate || generateRef.current || !studentId || !complete) return
    generateRef.current = true
    void generate().finally(() => {
      const next = new URLSearchParams(searchParams)
      next.delete('generate')
      setSearchParams(next, { replace: true })
    })
  }, [shouldGenerate, studentId, complete, generate, searchParams, setSearchParams])

  const plan = payload?.plan ?? null
  const serverOrder = useMemo(
    () => (plan?.items ?? []).map((item) => item.unit.unit_id),
    [plan],
  )
  const effectiveOrder = order ?? serverOrder
  const itemById = useMemo(() => {
    const map = new Map<string, NonNullable<typeof plan>['items'][number]>()
    for (const item of plan?.items ?? []) map.set(item.unit.unit_id, item)
    return map
  }, [plan])

  const highRisks = (payload?.risks ?? []).filter((risk) => risk.level === 'HIGH')
  const maxVolunteers = plan?.rule.max_volunteers ?? null
  const shortage = maxVolunteers !== null ? maxVolunteers - effectiveOrder.length : null

  const persist = useCallback(
    async (unitIds: string[], obeyOverride?: { unitId: string; value: boolean }) => {
      if (!planId) return
      setBusy(true)
      setError(null)
      try {
        const response = await api.plans.patchItems(planId, {
          items: unitIds.map((unitId) => ({
            unit_id: unitId,
            obey_adjustment:
              obeyOverride && obeyOverride.unitId === unitId
                ? obeyOverride.value
                : (itemById.get(unitId)?.obey_adjustment ?? null),
          })),
        })
        setBundle(response)
        setOrder(null)
      } catch (caught) {
        setError(caught)
        setOrder(null) // 失败就回到服务端为准，绝不留下"界面与后端不一致"的状态
      } finally {
        setBusy(false)
      }
    },
    [planId, itemById, setBundle],
  )

  const move = useCallback(
    (from: number, to: number) => {
      if (to < 0 || to >= effectiveOrder.length || from === to) return
      const next = [...effectiveOrder]
      const [moved] = next.splice(from, 1)
      if (moved === undefined) return
      next.splice(to, 0, moved)
      setOrder(next)
      void persist(next)
    },
    [effectiveOrder, persist],
  )

  const remove = useCallback(
    (unitId: string) => {
      const next = effectiveOrder.filter((item) => item !== unitId)
      setOrder(next)
      void persist(next)
    },
    [effectiveOrder, persist],
  )

  const add = useCallback(
    (unitId: string) => {
      if (effectiveOrder.includes(unitId)) return
      const next = [...effectiveOrder, unitId]
      setOrder(next)
      void persist(next)
    },
    [effectiveOrder, persist],
  )

  const setObey = useCallback(
    (unitId: string, value: boolean) => {
      setOrder(effectiveOrder)
      void persist(effectiveOrder, { unitId, value })
    },
    [effectiveOrder, persist],
  )

  // -------------------------------------------------------------------------
  if (!complete) {
    return (
      <div className="space-y-4">
        <h1 className="text-xl font-semibold">志愿表</h1>
        <div className="blocking-banner">
          <p className="blocking-banner-title">
            <span aria-hidden="true">⛔</span>档案未完成，无法生成志愿表
          </p>
          <Link to="/profile" className="btn-primary mt-3 inline-flex">
            去补齐档案
          </Link>
        </div>
      </div>
    )
  }

  return (
    <div className="space-y-5">
      <div className="flex flex-wrap items-end justify-between gap-3">
        <div>
          <h1 className="text-xl font-semibold">志愿表</h1>
          <p className="muted mt-1">
            {plan
              ? `${provinceLabel(plan.province)} · ${plan.rule.batch_name} · 最多 ${plan.rule.max_volunteers} 个志愿`
              : '还没有志愿表'}
          </p>
        </div>
        <div className="flex flex-wrap gap-2">
          <button type="button" className="btn-secondary" disabled={busy || !studentId} onClick={() => void generate()}>
            {plan ? '重新生成' : '生成志愿表'}
          </button>
          {planId && (
            <>
              <a
                className={`btn-secondary ${highRisks.length > 0 && !acknowledged ? 'pointer-events-none opacity-50' : ''}`}
                href={api.plans.exportUrl(planId, 'pdf')}
                aria-disabled={highRisks.length > 0 && !acknowledged}
              >
                导出 PDF
              </a>
              <a
                className={`btn-secondary ${highRisks.length > 0 && !acknowledged ? 'pointer-events-none opacity-50' : ''}`}
                href={api.plans.exportUrl(planId, 'xlsx')}
                aria-disabled={highRisks.length > 0 && !acknowledged}
              >
                导出 Excel
              </a>
              <Link className="btn-secondary" to="/report">
                打印报告
              </Link>
            </>
          )}
        </div>
      </div>

      {busy && <p className="muted" aria-live="polite">正在与后端同步志愿表…</p>}
      {!!loaded.error && (
        <ErrorNote
          title="读取志愿表失败"
          message={loaded.error instanceof Error ? loaded.error.message : String(loaded.error)}
          onRetry={loaded.reload}
        />
      )}
      {!!error && (
        <ErrorNote
          title="操作失败"
          message={
            error instanceof ApiError
              ? error.message
              : error instanceof Error
                ? error.message
                : String(error)
          }
        />
      )}

      {!plan && !busy && (
        <div className="card card-pad text-center">
          <p className="font-medium text-slate-700">还没有志愿表</p>
          <p className="muted mt-1">
            生成时会按冲稳保垫配额挑选候选，并强制让最后一档落在「保/垫」；
            你在推荐页加入的「意愿序」会作为排序意愿。
          </p>
        </div>
      )}

      {plan && (
        <>
          {highRisks.length > 0 && (
            <div className="blocking-banner" role="alert">
              <p className="blocking-banner-title">
                <span aria-hidden="true">⛔</span>
                存在 {highRisks.length} 个高风险项：导出与打印已暂时锁定
              </p>
              <p className="mt-2 text-sm text-rose-900">
                请先在下方的风险面板中逐条处理；确认理解后勾选下面的复选框即可解锁导出。
              </p>
              <label className="mt-3 flex items-center gap-2 text-sm font-medium text-rose-900">
                <input
                  type="checkbox"
                  checked={acknowledged}
                  onChange={(event) => setAcknowledged(event.target.checked)}
                />
                我已阅读并理解上述高风险项，仍要继续导出
              </label>
            </div>
          )}

          <div className="grid gap-5 lg:grid-cols-[2fr_1fr]">
            <div className="space-y-3">
              <div className="card card-pad">
                <div className="flex flex-wrap items-center justify-between gap-2">
                  <h2 className="card-title">
                    志愿顺序（{effectiveOrder.length}
                    {maxVolunteers !== null ? ` / ${maxVolunteers}` : ''}）
                  </h2>
                  <button type="button" className="btn-secondary" onClick={() => setShowAdd((value) => !value)}>
                    {showAdd ? '收起添加面板' : '添加志愿'}
                  </button>
                </div>
                <p className="muted mt-1">
                  平行志愿按填报顺序检索，请把最想去的志愿放在前面。
                  拖拽或使用上移/下移按钮调整；每次改动都会同步到后端并重算风险。
                </p>
                {shortage !== null && shortage > 0 && (
                  <p className="callout-warn mt-2 text-sm">
                    还差 {shortage} 个志愿未填。填满能显著降低滑档风险（省里给的容量不用就是浪费机会）。
                  </p>
                )}
              </div>

              {showAdd && (
                <AddPanel

                  existing={effectiveOrder}
                  onAdd={add}
                  studentId={studentId}
                />
              )}

              <ul className="space-y-3" aria-label="志愿列表（按填报顺序）">
                {effectiveOrder.map((unitId, index) => {
                  const item = itemById.get(unitId)
                  if (!item) return null
                  return (
                    <PlanRow
                      key={unitId}
                      item={item}
                      index={index}
                      total={effectiveOrder.length}
                      college={payload?.colleges?.[item.unit.college_id] ?? null}
                      hasAdjustment={plan.rule.has_major_adjustment}
                      studentRank={profile.rank}
                      dragging={dragIndex === index}
                      dropTarget={dropIndex === index && dragIndex !== index}
                      onDragStart={() => setDragIndex(index)}
                      onDragEnter={() => setDropIndex(index)}
                      onDragEnd={() => {
                        setDragIndex(null)
                        setDropIndex(null)
                      }}
                      onDrop={() => {
                        if (dragIndex !== null && dropIndex !== null && dragIndex !== dropIndex) {
                          move(dragIndex, dropIndex)
                        }
                        setDragIndex(null)
                        setDropIndex(null)
                      }}
                      onMove={move}
                      onRemove={() => remove(unitId)}
                      onToggleObey={(value) => setObey(unitId, value)}
                    />
                  )
                })}
              </ul>

              {effectiveOrder.length === 0 && (
                <p className="callout-warn">志愿表当前为空。空志愿表等于放弃本批次，请先添加志愿。</p>
              )}
            </div>

            <div className="space-y-5">
              <div className="card card-pad">
                <h2 className="card-title">梯度分布</h2>
                <div className="mt-2">
                  <GradientChart
                    distribution={plan.tier_distribution}
                    maxVolunteers={maxVolunteers}                  />
                </div>
                <p className="mt-2 text-xs text-slate-500">
                  「保/垫」偏少是正常的：安全闸门会把给不出 30% 余量的高概率单位降级为「稳」，
                  配额比例可能因候选不足而变化，但垫底志愿必须保留。
                </p>
              </div>

              <div className="card card-pad">
                <h2 className="card-title">风险扫描</h2>
                <div className="mt-2">
                  <RiskPanel
                    risks={payload?.risks ?? []}
                    violations={payload?.stats?.violations ?? []}
                    onLocate={(unitId) => scrollToElement(`unit-row-${unitId}`)}
                    emptyHint="未命中已知风险规则。这不等于「稳了」——请仍逐条核对招生章程。"
                  />
                </div>
              </div>

              {bundle?.warnings?.length ? <WarningList warnings={bundle.warnings} /> : null}

              <div className="card card-pad text-sm">
                <h2 className="card-title">本表依据</h2>
                <ul className="mt-2 space-y-1 text-slate-600">
                  <li>
                    批次规则：{plan.rule.batch_name}（{UNIT_TYPE_LABEL[plan.rule.unit_type] ?? plan.rule.unit_type}，
                    {plan.rule.max_volunteers} 个志愿，{plan.rule.is_parallel ? '平行志愿' : '顺序志愿'}）
                  </li>
                  <li>
                    你的位次：<span className="num">{formatRank(profile.rank)}</span>
                  </li>
                  <li>总效用：<span className="num">{plan.total_utility.toFixed(3)}</span></li>
                  <li>
                    规则来源：<SourceLink url={plan.rule.source_url} label="官方原文" />
                  </li>
                </ul>
                <p className="mt-2 text-xs text-slate-500">
                  逐项来源见「报告」页的数据来源清单（共 {formatNumber((payload?.plan.items.length ?? 0) * 3)} 条以内历史记录）。
                </p>
              </div>
            </div>
          </div>
        </>
      )}

      {autoGenerated && plan && (
        <p className="text-xs text-slate-400" aria-live="polite">
          已按你在推荐页设置的筛选与意愿序生成志愿表。
        </p>
      )}
    </div>
  )
}

/** 添加志愿面板：候选来自推荐接口 —— 与志愿表**同一份档案口径**（ADR-022）。 */
function AddPanel({
  existing,
  onAdd,
  studentId,
}: {
  existing: string[]
  onAdd: (unitId: string) => void
  studentId: string | null
}) {
  const candidates = useAsync(async () => {
    if (!studentId) return []
    const envelope = await api.recommend({
      student_id: studentId,
      // 不传 filters → 后端按档案偏好生成，与志愿表口径一致（ADR-022）
      limit: 300,
      include_too_risky: false,
    })
    return envelope.data.items
  }, [studentId])

  const available: RecommendItem[] = (candidates.data ?? []).filter(
    (item) => !existing.includes(item.unit.unit_id),
  )

  return (
    <div className="card card-pad">
      <h3 className="card-title">可添加的志愿（同一筛选口径，按分层与效用排序）</h3>
      <p className="muted mt-1 text-xs">
        这里列出的单位与后端候选池完全同源；被硬约束（选考/体检/语种/学费上限等）剔除的单位不会出现。
      </p>
      {candidates.loading && <p className="muted mt-2">加载中…</p>}
      {!!candidates.error && (
        <ErrorNote
          title="读取候选失败"
          message={candidates.error instanceof Error ? candidates.error.message : String(candidates.error)}
          onRetry={candidates.reload}
        />
      )}
      {!candidates.loading && available.length === 0 && (
        <p className="callout-muted mt-2">当前筛选下没有可添加的单位（可能都已加入，或数据覆盖不足）。</p>
      )}
      {available.length > 0 && (
        <ul className="mt-3 max-h-80 space-y-2 overflow-y-auto pr-1">
          {available.slice(0, 120).map((item) => (
            <li
              key={item.unit.unit_id}
              className="flex items-center justify-between gap-3 rounded-lg border border-slate-200 p-2 text-sm"
            >
              <div className="min-w-0">
                <p className="truncate font-medium text-slate-800">
                  {item.college?.name ?? item.unit.college_id} · {item.unit.major_name}
                </p>
                <p className="text-xs text-slate-500">
                  {item.probability_interval && item.probability_interval.length >= 2
                    ? `${((item.probability_interval[0] ?? 0) * 100).toFixed(0)}%–${((item.probability_interval[1] ?? 0) * 100).toFixed(0)}%`
                    : '概率不可用'}{' '}
                  · 计划 {formatPlanCount(item.unit.plan_count)} 人 · 学费 {formatTuition(item.unit.tuition)}
                </p>
              </div>
              <button type="button" className="btn-secondary shrink-0" onClick={() => onAdd(item.unit.unit_id)}>
                加入
              </button>
            </li>
          ))}
        </ul>
      )}
    </div>
  )
}
